# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

source 'https://cdn.cocoapods.org/'
source 'https://github.com/CocoaPods/Specs.git'

  def common_version
  '1.7.0-rc1'
  end

  def pod_ailplayer
    pod 'AliPlayerSDK_iOS', '5.4.4.0'
    pod 'AliPlayerSDK_iOS_ARTC', '5.4.4.0'
    pod 'RtsSDK', '1.9.0'
  end

#低代码音视频工厂互动直播标准接入主播侧的实现逻辑
target 'NormalLiveRoomForAnchor' do
  
  pod 'Masonry'

  #阿里云低代码音视频工厂互动直播标准接入入口库
  pod 'AliInteractiveRoomBundle', common_version

  pod 'AliInteractiveLiveCore', common_version
  pod 'AlivcLivePusher', '4.2.1'
  pod 'RtsSDK', '1.9.0'
  pod 'Queen', '1.9.1-official-pro'

end














