# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

#ali_source 'alibaba-specs'
#ali_source 'alibaba-specs-mirror'

target 'AliInteractiveRoomDemo' do
  # Pods for AliInteractiveRoomDemo
  pod 'Masonry'
#  pod 'AliHAAdapter4Internal',   '10.0.5.51-only-crash-dt'
#  pod 'AliHACore', '10.0.4.11-remove-uiwebview'
#  pod 'AliHAPerformanceMonitor', '10.0.5.26'
#  pod 'UserTrack', '6.3.6.98-noIdfa-nowv'
#  pod 'tnet', '3.1.10.4'
end
