# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

source 'https://cdn.cocoapods.org/'
source 'https://github.com/CocoaPods/Specs.git'

  def common_version
  '1.5.0'
  end

  def pod_ailplayer
    pod 'AliPlayerSDK_iOS', '5.4.3.0-15301379'
    pod 'AliPlayerSDK_iOS_ARTC', '5.4.3.0-15301379'
    pod 'RtsSDK', '1.9.0'
  end

#基于场景化SDK的互动直播的主播侧实现逻辑
target 'NormalLiveRoomForAnchor' do
  
  pod 'Masonry'

  #阿里云低代码音视频工厂总入口库
  pod 'AliInteractiveRoomBundle', common_version

  #阿里云低代码音视频工厂主播推流端相关库
  pod 'AliInteractiveLiveCore', common_version
  pod 'AlivcLivePusher', '4.2.1'
  pod 'RtsSDK', '1.9.0'
  pod 'Queen', '1.4.1-official-lite'

end

#基于场景化SDK的互动直播的观众侧实现逻辑
 target 'NormalLiveRoomForAudience' do
   
   pod 'Masonry'
  
   #阿里云低代码音视频工厂总入口库
   pod 'AliInteractiveRoomBundle', common_version

   #阿里云低代码音视频工厂观众拉流相关库
   pod 'AliInteractiveVideoPlayerCore', common_version
   pod_ailplayer
  
 end

#基于互动直播样板间的主播侧实现逻辑
 target 'StandardLiveRoomForAnchor' do
   
   pod 'Masonry'

   #阿里云低代码音视频工厂总入口库
   pod 'AliInteractiveRoomBundle', common_version

   #阿里云低代码音视频工厂主播推流端相关库
   pod 'AliInteractiveLiveCore', common_version
   pod 'AlivcLivePusher', '4.2.1'
   pod 'Queen', '1.4.1-official-lite'
   pod 'RtsSDK', '1.9.0'

   #阿里云低代码音视频工厂互动直播样板间相关库
   pod 'AliStandardLiveRoomBundle', common_version
  
 end

#基于互动直播样板间的观众侧实现逻辑
 target 'StandardLiveRoomForAudience' do
   
   pod 'Masonry'
  
   #阿里云低代码音视频工厂总入口库
   pod 'AliInteractiveRoomBundle', common_version

   #阿里云低代码音视频工厂观众拉流相关库
   pod 'AliInteractiveVideoPlayerCore', common_version
   pod_ailplayer

   #阿里云低代码音视频工厂互动直播样板间相关库
   pod 'AliStandardLiveRoomBundle', common_version
 end


#基于互动课堂样板间的老师侧实现逻辑（以大班课为例）
target 'StandardClassroomForTeacher' do
     pod 'Masonry'
     pod 'MJRefresh'
     pod 'LEEAlert'
     
     #阿里云低代码音视频工厂互动课堂样板间相关库，必需
     pod 'AliStandardClassroomBundle', common_version
     
     #阿里云低代码音视频工厂核心依赖库，必需
     pod 'AliInteractiveRoomBundle', common_version
     
     #阿里云低代码音视频工厂RTC相关库
     pod 'AliInteractiveRTCCore', common_version
     pod 'AliRTCSdk', '2.5.3'

     #阿里云低代码音视频工厂白板能力相关库，如果没有使用，则不需要
     pod 'AliInteractiveWhiteBoardCore', common_version

     #阿里云低代码音视频工厂文档能力相关库，如果没有使用，则不需要
     pod 'AliInteractiveDocumentCore', common_version
     
  end

#基于互动课堂样板间的学生侧实现逻辑（以大班课为例）
target 'StandardClassroomForStudents' do
     pod 'Masonry'
     pod 'MJRefresh'
     pod 'LEEAlert'
     
     #阿里云低代码音视频工厂互动课堂样板间相关库
     pod 'AliStandardClassroomBundle', common_version
     
     #阿里云低代码音视频工厂核心依赖库
     pod 'AliInteractiveRoomBundle', common_version
     
     #阿里云低代码音视频工厂RTC相关库
     pod 'AliInteractiveRTCCore', common_version
     pod 'AliRTCSdk', '2.5.3'

     #阿里云低代码音视频工厂白板能力相关库，如果没有使用白板能力，则不需要
     pod 'AliInteractiveWhiteBoardCore', common_version
     
     #阿里云低代码音视频工厂观众拉流相关库，如果没有旁路直播（小班课），则不需要这些
     pod 'AliInteractiveVideoPlayerCore', common_version
     pod_ailplayer
  
  end

#基于场景化SDK的互动课堂老师侧实现逻辑（以大班课为例）
target 'NormalClassroomForTeacher' do
  
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'LEEAlert'
  
  #阿里云低代码音视频工厂核心依赖库，必需
  pod 'AliInteractiveRoomBundle', common_version
  
  #阿里云低代码音视频工厂RTC相关库
  pod 'AliInteractiveRTCCore', common_version
  pod 'AliRTCSdk', '2.5.3'

  #阿里云低代码音视频工厂白板能力相关库，如果没有使用，则不需要
  pod 'AliInteractiveWhiteBoardCore', common_version

  #阿里云低代码音视频工厂文档能力相关库，如果没有使用，则不需要
  pod 'AliInteractiveDocumentCore', common_version
  
  end

#基于场景化SDK的互动课堂学生侧实现逻辑（以大班课为例）
target 'NormalClassroomForStudents' do
  
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'LEEAlert'
  
  #阿里云低代码音视频工厂核心依赖库
  pod 'AliInteractiveRoomBundle', common_version
  
  #阿里云低代码音视频工厂RTC相关库
  pod 'AliInteractiveRTCCore', common_version
  pod 'AliRTCSdk', '2.5.3'

  #阿里云低代码音视频工厂白板能力相关库，如果没有使用白板能力，则不需要
  pod 'AliInteractiveWhiteBoardCore', common_version

  #阿里云低代码音视频工厂文档能力相关库，如果没有使用文档能力，则不需要
  pod 'AliInteractiveDocumentCore', common_version
  
  #阿里云低代码音视频工厂观众拉流相关库，如果没有旁路直播（小班课），则不需要这些
  pod 'AliInteractiveVideoPlayerCore', common_version
  pod_ailplayer
  end












