# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

source 'https://cdn.cocoapods.org/'
source 'https://github.com/CocoaPods/Specs.git'

  def common_version
  '1.6.0-rc3'
  end

  def pod_ailplayer
    pod 'AliPlayerSDK_iOS', '5.4.4.0'
    pod 'AliPlayerSDK_iOS_ARTC', '5.4.4.0'
    pod 'RtsSDK', '1.9.0'
  end

#低代码音视频工厂互动直播标准接入主播侧的实现逻辑
target 'NormalLiveRoomForAnchor' do
  
  pod 'Masonry'

  #阿里云低代码音视频工厂互动直播标准接入入口库
  pod 'AliInteractiveRoomBundle', common_version

  pod 'AliInteractiveLiveCore', common_version
  pod 'AlivcLivePusher', '4.2.1'
  pod 'RtsSDK', '1.9.0'
  pod 'Queen', '1.4.1-official-lite'

end

#低代码音视频工厂互动直播标准接入观众侧实现逻辑
 target 'NormalLiveRoomForAudience' do
   
   pod 'Masonry'
  
   #阿里云低代码音视频工厂互动直播标准接入入口库
   pod 'AliInteractiveRoomBundle', common_version

   pod 'AliInteractiveVideoPlayerCore', common_version
   pod_ailplayer
  
 end

#基于互动直播低代码主播侧实现逻辑
 target 'StandardLiveRoomForAnchor' do
   
   pod 'Masonry'
   
   #阿里云低代码音视频工厂互动直播低代码入口库
   pod 'AliStandardLiveRoomBundle', common_version

   pod 'AliInteractiveRoomBundle', common_version
   pod 'AliInteractiveLiveCore', common_version
   pod 'AlivcLivePusher', '4.2.1'
   pod 'Queen', '1.4.1-official-lite'
   pod 'RtsSDK', '1.9.0'

   
  
 end

#基于互动直播低代码接入的观众侧实现逻辑
 target 'StandardLiveRoomForAudience' do
   
   pod 'Masonry'
  
  #阿里云低代码音视频工厂互动直播低代码入口库
  pod 'AliStandardLiveRoomBundle', common_version

  pod 'AliInteractiveRoomBundle', common_version
  pod 'AliInteractiveVideoPlayerCore', common_version
  pod_ailplayer
  pod 'AliInteractiveRTCCore', common_version
  pod 'AliRTCSdk', '2.5.3'
 end


#基于互动课堂低代码接入的老师侧实现逻辑（以大班课为例）
target 'StandardClassroomForTeacher' do
     pod 'Masonry'
     pod 'MJRefresh'
     pod 'LEEAlert'
     
     #阿里云低代码音视频工厂互动课堂低代码入口库，必需
     pod 'AliStandardClassroomBundle', common_version
     
     pod 'AliInteractiveRoomBundle', common_version
     pod 'AliInteractiveRTCCore', common_version
     pod 'AliRTCSdk', '2.5.3'
     pod 'AliInteractiveWhiteBoardCore', common_version
     pod 'AliInteractiveDocumentCore', common_version
     
  end

#基于互动课堂样板间低代码接入的学生侧实现逻辑（以大班课为例）
target 'StandardClassroomForStudents' do
     pod 'Masonry'
     pod 'MJRefresh'
     pod 'LEEAlert'
     
     #阿里云低代码音视频工厂互动课堂低代码接入入口库
     pod 'AliStandardClassroomBundle', common_version
     
     pod 'AliInteractiveRoomBundle', common_version
     pod 'AliInteractiveRTCCore', common_version
     pod 'AliRTCSdk', '2.5.3'
     pod 'AliInteractiveWhiteBoardCore', common_version
     pod 'AliInteractiveVideoPlayerCore', common_version
     pod_ailplayer
  
  end

#低代码音视频工厂互动课堂标准接入老师侧实现逻辑（以大班课为例）
target 'NormalClassroomForTeacher' do
  
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'LEEAlert'
  
  #阿里云低代码音视频工厂互动课堂标准接入入口库，必需
  pod 'AliInteractiveRoomBundle', common_version
  
  pod 'AliInteractiveRTCCore', common_version
  pod 'AliRTCSdk', '2.5.3'

  pod 'AliInteractiveWhiteBoardCore', common_version

  pod 'AliInteractiveDocumentCore', common_version
  
  end

#低代码音视频工厂互动课堂标准接入学生侧实现逻辑（以大班课为例）
target 'NormalClassroomForStudents' do
  
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'LEEAlert'
  
  #阿里云低代码音视频工厂互动课堂标准接入入口库
  pod 'AliInteractiveRoomBundle', common_version
  
  pod 'AliInteractiveRTCCore', common_version
  pod 'AliRTCSdk', '2.5.3'

  pod 'AliInteractiveWhiteBoardCore', common_version

  pod 'AliInteractiveDocumentCore', common_version
  
  pod 'AliInteractiveVideoPlayerCore', common_version
  pod_ailplayer
  end












