# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '10.0'

source 'https://cdn.cocoapods.org/'
source 'https://github.com/CocoaPods/Specs.git'

target 'InteractiveMessageForCreator' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  pod 'Masonry'
   
  # Pods for InteractiveMessageForCreator
  pod 'AliInteractiveRoomBundle', '1.7.0-rc1'

end
